### PR TITLE
Fix security issues

### PR DESCRIPTION
**Pull request by timmson**
**Tests**
```
npm run test

transmission
    √ can instantiate a new instance
    status definition
      √ should have correct status
    methods
      - should set properties
      √ should get all torrents
      √ should get all active torrents
      √ should add torrent from file path (233ms)
      √ should add torrent from url (459ms)
      √ should rename the torrent (330ms)
      √ should stop all torrents (2357ms)
      √ should stop a torrent
      - should start working torrents
      - should start working torrents immediately
      - should reannounce to the tracker
      - should set client session info
      √ should get client session info
      √ should get client session stats


  11 passing (3s)
  5 pending
```

**Lint**
```
npm run lint
standard: Use JavaScript Standard Style (https://standardjs.com)
 test\transmission.spec.js:1:23: 'afterEach' is defined but never used.
 test\transmission.spec.js:41:9: 'sampleHash' is assigned a value but never used.
```

**Security audit**
```
npm audit
                                                                                
=== npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 494 scanned packages
```

### CODE REVIEW

**Comment by grantholle** [comment]
Thanks for this housecleaning

**Comment by timmson** [comment]
You are welcome:) Could you publish new version to npm registry?

**Comment by grantholle** [comment]
Just published `1.1.3`

**Comment by timmson** [comment]
Thx, fetched it

**Pull request merged**
